<?php

/**
 * BulletinTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BulletinTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BulletinTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BulletinType');
    }
}