<?php

/**
 * ConfirmationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfirmationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfirmationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Confirmation');
    }
}