<?php

/**
 * SubscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subscription');
    }
}