BulletinType:
  connection: doctrine
  tableName: BulletinType
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Subscription:
      local: id
      foreign: bulletin_type_id
      type: many
Confirmation:
  actAs: [Timestampable]
  connection: doctrine
  tableName: Confirmation
  columns:
    user_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    hash:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    User:
      local: user_id
      foreign: id
      type: one
Subscription:
  actAs: [Timestampable]
  connection: doctrine
  tableName: Subscription
  columns:
    user_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    bulletin_type_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
  relations:
    User:
      local: user_id
      foreign: id
      type: one
    BulletinType:
      local: bulletin_type_id
      foreign: id
      type: one
User:
  actAs: [Timestampable]
  connection: doctrine
  tableName: User
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    username:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    lastname:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    gender:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    passwd:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    lastlogin:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  indexes:
    username_unique:
      fields:
        username:
          sorting: ASC
      type: unique
    email:
      fields:
        email:
          sorting: ASC
  relations:
    Confirmation:
      local: id
      foreign: user_id
      type: one
    Subscription:
      local: id
      foreign: user_id
      type: many
